# Generated by Django 4.1.3 on 2023-06-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='year',
            field=models.IntegerField(),
        ),
    ]
