# Generated by Django 4.1.3 on 2023-06-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_accident_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='date',
        ),
    ]
