# Generated by Django 4.1.3 on 2023-06-08 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_accident_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='year',
        ),
    ]
