# Generated by Django 4.1.3 on 2023-06-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_accident_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='latitud',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='accident',
            name='longitud',
            field=models.FloatField(default=0),
        ),
    ]
